# Generated by Django 2.2.3 on 2019-08-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190731_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ImageField(default=1, upload_to='media/', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='top_image',
            field=models.ImageField(blank=True, max_length=30, upload_to='', verbose_name='トップ画像'),
        ),
    ]
