# Generated by Django 2.2.3 on 2019-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190801_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_a',
            field=models.URLField(blank=True, max_length=150, verbose_name='Instagramアカウント'),
        ),
    ]
