# Generated by Django 2.2.3 on 2019-08-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20190801_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instagram_a',
            new_name='instagram',
        ),
    ]
