# Generated by Django 2.2.3 on 2019-08-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20190801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='top_image',
            field=models.ImageField(upload_to='media/', verbose_name='トップ画像'),
        ),
    ]
