# Generated by Django 2.2.3 on 2019-08-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20190805_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=150, verbose_name='活動範囲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=150, verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='user',
            name='top_image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='トップ画像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, choices=[('1', '活動領域を選択して下さい。'), ('2', 'オンライン'), ('3', '東京都')], verbose_name='Twitterアカウント'),
        ),
    ]
