# Generated by Django 2.2.3 on 2019-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20190805_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('1', 'オンライン'), ('2', '北海道'), ('3', '青森県'), ('4', '岩手県'), ('5', '宮城県'), ('6', '秋田県'), ('7', '山形県'), ('8', '福島県'), ('9', '茨城県'), ('10', '栃木県'), ('11', '群馬県'), ('12', '埼玉県'), ('13', '千葉県'), ('14', '東京都'), ('15', '神奈川県'), ('16', '新潟県'), ('17', '富山県'), ('18', '石川県'), ('19', '福井県'), ('20', '山梨県'), ('21', '長野県'), ('22', '岐阜県'), ('23', '静岡県'), ('24', '愛知県'), ('25', '三重県'), ('26', '滋賀県'), ('27', '京都府'), ('28', '大阪府'), ('29', '兵庫県'), ('30', '奈良県'), ('31', '和歌山県'), ('32', '鳥取県'), ('33', '島根県'), ('34', '岡山県'), ('35', '広島県'), ('36', '山口県'), ('37', '徳島県'), ('38', '香川県'), ('39', '愛媛県'), ('40', '高知県'), ('41', '福岡県'), ('42', '佐賀県'), ('43', '長崎県'), ('44', '熊本県'), ('45', '大分県'), ('46', '宮崎県'), ('47', '鹿児島県'), ('48', '沖縄県')], max_length=150, verbose_name='活動範囲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=30, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_fee',
            field=models.CharField(choices=[('1', '応相談'), ('2', '無料'), ('3', '〜10,000円'), ('4', '10,000〜50,000円'), ('5', '50,000〜100,000円'), ('6', '100,000〜500,000円'), ('7', '500,000円以上から')], max_length=20, verbose_name='依頼料'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, choices=[('1', '活動領域を選択して下さい。'), ('2', 'オンライン'), ('3', '東京都')], max_length=150, verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitterアカウント'),
        ),
    ]
