# Generated by Django 2.2.3 on 2019-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20190807_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ImageField(default=1, upload_to='', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, choices=[('1', 'Webデザイナー'), ('2', 'プログラマー(フロントサイド)'), ('3', 'プログラマー(サーバーサイド)'), ('4', 'デザイナー'), ('5', 'フォトグラファー'), ('6', 'イラストレーター'), ('7', 'ライター'), ('8', 'ブロガー')], max_length=150, verbose_name='スキル'),
        ),
    ]
