# Generated by Django 2.2.3 on 2019-08-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20190814_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.AlterField(
            model_name='user',
            name='request_fee',
            field=models.CharField(choices=[('1', '応相談'), ('2', '無料'), ('3', '〜10,000円'), ('4', '10,000円〜'), ('5', '50,000円〜'), ('6', '100,000円〜'), ('7', '500,000円〜')], max_length=20, verbose_name='依頼料'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, choices=[('1', 'Webデザイナー'), ('2', 'PG(フロントサイド)'), ('3', 'PG(サーバーサイド)'), ('4', 'デザイナー'), ('5', 'フォトグラファー'), ('6', 'イラストレーター'), ('7', 'ライター'), ('8', 'ブロガー')], max_length=150, verbose_name='スキル'),
        ),
    ]
